# Generated by Django 3.0.5 on 2020-04-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.99, help_text='A number between 0 and 1', max_digits=2),
        ),
    ]
