# Generated by Django 3.0.5 on 2020-05-06 19:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200507_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 19, 51, 6, 585565, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='edit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 19, 51, 6, 585603, tzinfo=utc)),
        ),
    ]
