# Generated by Django 3.0.5 on 2020-05-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_remove_post_edit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
