# Generated by Django 3.0.5 on 2020-05-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_auto_20200510_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create_date',
        ),
    ]
