# Generated by Django 3.0.5 on 2020-05-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_remove_post_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='edit_date',
        ),
    ]
