# Generated by Django 3.0.5 on 2020-05-10 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_auto_20200510_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
