# Generated by Django 3.0.5 on 2020-05-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0026_post_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_joined',
        ),
    ]
