# Generated by Django 3.0.5 on 2020-05-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0030_auto_20200510_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-id',)},
        ),
    ]
