# Generated by Django 3.0.5 on 2020-05-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0033_post_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_created',)},
        ),
    ]
