# Generated by Django 3.0.5 on 2020-05-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0034_auto_20200510_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
