# Generated by Django 3.0.4 on 2020-04-03 10:50

from django.conf import settings
from django.db import migrations, models
import page.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('about', models.TextField(blank=True, max_length=2000, verbose_name='about')),
                ('num_chasers', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[page.validators.price_validator])),
                ('chasers', models.ManyToManyField(blank=True, related_name='chased_pages', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(related_name='page', to=settings.AUTH_USER_MODEL)),
                ('special_users', models.ManyToManyField(blank=True, related_name='special_subscriptions', related_query_name='special_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-num_chasers',),
            },
        ),
    ]
