# Generated by Django 3.0 on 2020-03-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='budget',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=10),
        ),
    ]
